name = "bierinckx-shop"
main = "src/worker.js"
compatibility_date = "2026-06-28"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[[routes]]
pattern = "bierinckx.com"
custom_domain = true

[[routes]]
pattern = "www.bierinckx.com"
custom_domain = true

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "856d92e4a0914013b150e540644306c7"
